# This file has been generated by node2nix 1.2.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "slasp";
    packageName = "slasp";
    version = "0.0.4";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      description = "SugarLess Asynchronous Structured Programming library with Object Oriented Programming Support";
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}